export interface Team {
  id: string
  name: string
  logoPath: string
}

// Lista completa de todos os times
export const ALL_TEAMS: Team[] = [
  { id: "abc", name: "ABC", logoPath: "/escudos_2025/abc.svg" },
  { id: "agua_santa", name: "Água Santa", logoPath: "/escudos_2025/agua_santa.svg" },
  { id: "america_de_pedrinhas", name: "América de Pedrinhas", logoPath: "/escudos_2025/america_de_pedrinhas.png" },
  { id: "america_rj", name: "América-RJ", logoPath: "/escudos_2025/america_rj.svg" },
  { id: "america-mg", name: "América-MG", logoPath: "/escudos_2025/america-mg.png" },
  { id: "america-rn", name: "América-RN", logoPath: "/escudos_2025/america-rn.svg" },
  { id: "araguacema", name: "Araguacema", logoPath: "/escudos_2025/araguacema.png" },
  { id: "aster", name: "Aster", logoPath: "/escudos_2025/aster.png" },
  { id: "athletico-pr", name: "Athletico-PR", logoPath: "/escudos_2025/athletico-pr.svg" },
  { id: "atletico_guaratingueta", name: "Atlético Guaratinguetá", logoPath: "/escudos_2025/atletico_guaratingueta.png" },
  { id: "atletico-go", name: "Atlético-GO", logoPath: "/escudos_2025/atletico-go.svg" },
  { id: "atletico-mg", name: "Atlético-MG", logoPath: "/escudos_2025/atletico-mg.svg" },
  { id: "audax-sp", name: "Audax-SP", logoPath: "/escudos_2025/audax-sp.svg" },
  { id: "avai", name: "Avaí", logoPath: "/escudos_2025/avai.svg" },
  { id: "azuriz", name: "Azuriz", logoPath: "/escudos_2025/azuriz.svg" },
  { id: "bahia", name: "Bahia", logoPath: "/escudos_2025/bahia.svg" },
  { id: "barra-sc", name: "Barra-SC", logoPath: "/escudos_2025/barra-sc.svg" },
  { id: "boavista", name: "Boavista", logoPath: "/escudos_2025/boavista.png" },
  { id: "botafogo", name: "Botafogo", logoPath: "/escudos_2025/botafogo.svg" },
  { id: "botafogo-sp", name: "Botafogo-SP", logoPath: "/escudos_2025/botafogo-sp.svg" },
  { id: "bragantino", name: "Bragantino", logoPath: "/escudos_2025/bragantino.svg" },
  { id: "brasiliense", name: "Brasiliense", logoPath: "/escudos_2025/brasiliense.png" },
  { id: "ca_bandeirante", name: "CA Bandeirante", logoPath: "/escudos_2025/ca_bandeirante.png" },
  { id: "canaa", name: "Canaã", logoPath: "/escudos_2025/canaa.png" },
  { id: "capitao_poco", name: "Capitão Poço", logoPath: "/escudos_2025/capitao_poco.png" },
  { id: "capivariano", name: "Capivariano", logoPath: "/escudos_2025/capivariano.png" },
  { id: "ceara", name: "Ceará", logoPath: "/escudos_2025/ceara.svg" },
  { id: "coimbra", name: "Coimbra", logoPath: "/escudos_2025/coimbra.png" },
  { id: "comercial_de_tiete", name: "Comercial de Tietê", logoPath: "/escudos_2025/comercial_de_tiete.png" },
  { id: "comercial-sp", name: "Comercial-SP", logoPath: "/escudos_2025/comercial-sp.svg" },
  { id: "corinthians", name: "Corinthians", logoPath: "/escudos_2025/corinthians.svg" },
  { id: "coritiba", name: "Coritiba", logoPath: "/escudos_2025/coritiba.svg" },
  { id: "crb", name: "CRB", logoPath: "/escudos_2025/crb.svg" },
  { id: "criciuma", name: "Criciúma", logoPath: "/escudos_2025/criciuma.svg" },
  { id: "cruzeiro", name: "Cruzeiro", logoPath: "/escudos_2025/cruzeiro.svg" },
  { id: "cruzeiro-pb", name: "Cruzeiro-PB", logoPath: "/escudos_2025/cruzeiro-pb.png" },
  { id: "cuiaba", name: "Cuiabá", logoPath: "/escudos_2025/cuiaba.svg" },
  { id: "desportivo_brasil", name: "Desportivo Brasil", logoPath: "/escudos_2025/desportivo_brasil.png" },
  { id: "dom_bosco", name: "Dom Bosco", logoPath: "/escudos_2025/dom_bosco.svg" },
  { id: "dourados", name: "Dourados", logoPath: "/escudos_2025/dourados.png" },
  { id: "ec_sao_bernardo", name: "EC São Bernardo", logoPath: "/escudos_2025/ec_sao_bernardo.png" },
  { id: "estrela_de_marco", name: "Estrela de Marco", logoPath: "/escudos_2025/estrela_de_marco.png" },
  { id: "falcon", name: "Falcon", logoPath: "/escudos_2025/falcon.png" },
  { id: "fast", name: "Fast", logoPath: "/escudos_2025/fast.png" },
  { id: "fc_cascavel", name: "FC Cascavel", logoPath: "/escudos_2025/fc_cascavel.svg" },
  { id: "ferroviaria", name: "Ferroviária", logoPath: "/escudos_2025/ferroviaria.svg" },
  { id: "ferroviario", name: "Ferroviário", logoPath: "/escudos_2025/ferroviario.svg" },
  { id: "flamengo", name: "Flamengo", logoPath: "/escudos_2025/flamengo.svg" },
  { id: "flamengo-sp", name: "Flamengo-SP", logoPath: "/escudos_2025/flamengo-sp.png" },
  { id: "floresta", name: "Floresta", logoPath: "/escudos_2025/floresta.svg" },
  { id: "fluminense", name: "Fluminense", logoPath: "/escudos_2025/fluminense.svg" },
  { id: "forca_e_luz", name: "Força e Luz", logoPath: "/escudos_2025/forca_e_luz.png" },
  { id: "fortaleza", name: "Fortaleza", logoPath: "/escudos_2025/fortaleza.svg" },
  { id: "francana", name: "Francana", logoPath: "/escudos_2025/francana.png" },
  { id: "genus", name: "Genus", logoPath: "/escudos_2025/genus.png" },
  { id: "goias", name: "Goiás", logoPath: "/escudos_2025/goias.svg" },
  { id: "gremio", name: "Grêmio", logoPath: "/escudos_2025/gremio.svg" },
  { id: "guarani", name: "Guarani", logoPath: "/escudos_2025/guarani.svg" },
  { id: "hercilio_luz", name: "Hercílio Luz", logoPath: "/escudos_2025/hercilio_luz.svg" },
  { id: "iape", name: "Iapé", logoPath: "/escudos_2025/iape.png" },
  { id: "ibrachina", name: "Ibrachina", logoPath: "/escudos_2025/ibrachina.png" },
  { id: "imperatriz", name: "Imperatriz", logoPath: "/escudos_2025/imperatriz.svg" },
  { id: "inter_de_limeira", name: "Inter de Limeira", logoPath: "/escudos_2025/inter_de_limeira.svg" },
  { id: "inter_de_minas", name: "Inter de Minas", logoPath: "/escudos_2025/inter_de_minas.png" },
  { id: "internacional", name: "Internacional", logoPath: "/escudos_2025/internacional.svg" },
  { id: "itapirense", name: "Itapirense", logoPath: "/escudos_2025/itapirense.svg" },
  { id: "ituano", name: "Ituano", logoPath: "/escudos_2025/ituano.svg" },
  { id: "jacioba", name: "Jaciobá", logoPath: "/escudos_2025/jacioba.svg" },
  { id: "juventude", name: "Juventude", logoPath: "/escudos_2025/juventude.svg" },
  { id: "juventus-sp", name: "Juventus-SP", logoPath: "/escudos_2025/juventus-sp.svg" },
  { id: "linense", name: "Linense", logoPath: "/escudos_2025/linense.png" },
  { id: "madureira", name: "Madureira", logoPath: "/escudos_2025/madureira.svg" },
  { id: "marcilio_dias", name: "Marcílio Dias", logoPath: "/escudos_2025/marcilio_dias.svg" },
  { id: "mazagao", name: "Mazagão", logoPath: "/escudos_2025/mazagao.png" },
  { id: "mirassol", name: "Mirassol", logoPath: "/escudos_2025/mirassol.svg" },
  { id: "monte_roraima", name: "Monte Roraima", logoPath: "/escudos_2025/monte_roraima.png" },
  { id: "nacional-sp", name: "Nacional-SP", logoPath: "/escudos_2025/nacional-sp.png" },
  { id: "nautico", name: "Náutico", logoPath: "/escudos_2025/nautico.svg" },
  { id: "nautico-rr", name: "Náutico-RR", logoPath: "/escudos_2025/nautico-rr.svg" },
  { id: "nova_iguacu", name: "Nova Iguaçu", logoPath: "/escudos_2025/nova_iguacu.svg" },
  { id: "novorizontino", name: "Novorizontino", logoPath: "/escudos_2025/novorizontino.svg" },
  { id: "oeste", name: "Oeste", logoPath: "/escudos_2025/oeste.png" },
  { id: "operario_de_caarapo", name: "Operário de Caarapó", logoPath: "/escudos_2025/operario_de_caarapo.png" },
  { id: "operario-pr", name: "Operário-PR", logoPath: "/escudos_2025/operario-pr.svg" },
  { id: "palmeiras", name: "Palmeiras", logoPath: "/escudos_2025/palmeiras.svg" },
  { id: "piaui", name: "Piauí", logoPath: "/escudos_2025/piaui.svg" },
  { id: "picos", name: "Picos", logoPath: "/escudos_2025/picos.svg" },
  { id: "ponte_preta", name: "Ponte Preta", logoPath: "/escudos_2025/ponte_preta.svg" },
  { id: "porto_velho", name: "Porto Velho", logoPath: "/escudos_2025/porto_velho.svg" },
  { id: "porto_vitoria", name: "Porto Vitória", logoPath: "/escudos_2025/porto_vitoria.png" },
  { id: "portuguesa", name: "Portuguesa", logoPath: "/escudos_2025/portuguesa.svg" },
  { id: "portuguesa_santista", name: "Portuguesa Santista", logoPath: "/escudos_2025/portuguesa_santista.svg" },
  { id: "real_brasilia", name: "Real Brasília", logoPath: "/escudos_2025/real_brasilia.svg" },
  { id: "referencia", name: "Referência", logoPath: "/escudos_2025/referencia.png" },
  { id: "retro", name: "Retrô", logoPath: "/escudos_2025/retro.svg" },
  { id: "rio_branco-ac", name: "Rio Branco-AC", logoPath: "/escudos_2025/rio_branco-ac.png" },
  { id: "rio_branco-es", name: "Rio Branco-ES", logoPath: "/escudos_2025/rio_branco-es.svg" },
  { id: "santa_cruz", name: "Santa Cruz", logoPath: "/escudos_2025/santa_cruz.svg" },
  { id: "santa_cruz-ac", name: "Santa Cruz-AC", logoPath: "/escudos_2025/santa_cruz-ac.svg" },
  { id: "santa_fe-sp", name: "Santa Fé-SP", logoPath: "/escudos_2025/santa_fe-sp.png" },
  { id: "santo_andre", name: "Santo André", logoPath: "/escudos_2025/santo_andre.svg" },
  { id: "santos", name: "Santos", logoPath: "/escudos_2025/santos.svg" },
  { id: "sao_bento", name: "São Bento", logoPath: "/escudos_2025/sao_bento.svg" },
  { id: "sao_carlos", name: "São Carlos", logoPath: "/escudos_2025/sao_carlos.png" },
  { id: "sao_jose-rs", name: "São José-RS", logoPath: "/escudos_2025/sao_jose-rs.svg" },
  { id: "sao_paulo", name: "São Paulo", logoPath: "/escudos_2025/sao_paulo.svg" },
  { id: "sergipe", name: "Sergipe", logoPath: "/escudos_2025/sergipe.svg" },
  { id: "serra_branca", name: "Serra Branca", logoPath: "/escudos_2025/serra_branca.png" },
  { id: "sfera", name: "Sfera", logoPath: "/escudos_2025/sfera.svg" },
  { id: "sport", name: "Sport", logoPath: "/escudos_2025/sport.svg" },
  { id: "tanabi", name: "Tanabi", logoPath: "/escudos_2025/tanabi.png" },
  { id: "taubate", name: "Taubaté", logoPath: "/escudos_2025/taubate.png" },
  { id: "tirol", name: "Tirol", logoPath: "/escudos_2025/tirol.svg" },
  { id: "trindade", name: "Trindade", logoPath: "/escudos_2025/trindade.png" },
  { id: "tuna_luso", name: "Tuna Luso", logoPath: "/escudos_2025/tuna_luso.svg" },
  { id: "uniao_suzano", name: "União Suzano", logoPath: "/escudos_2025/uniao_suzano.png" },
  { id: "uniao-to", name: "União-TO", logoPath: "/escudos_2025/uniao-to.svg" },
  { id: "vasco", name: "Vasco", logoPath: "/escudos_2025/vasco.svg" },
  { id: "vila_nova", name: "Vila Nova", logoPath: "/escudos_2025/vila_nova.svg" },
  { id: "vitoria", name: "Vitória", logoPath: "/escudos_2025/vitoria.svg" },
  { id: "vitoria_da_conquista", name: "Vitória da Conquista", logoPath: "/escudos_2025/vitoria_da_conquista.png" },
  { id: "votoraty", name: "Votoraty", logoPath: "/escudos_2025/votoraty.png" },
  { id: "votuporanguense", name: "Votuporanguense", logoPath: "/escudos_2025/votuporanguense.svg" },
  { id: "xv_de_jau", name: "XV de Jaú", logoPath: "/escudos_2025/xv_de_jau.svg" },
  { id: "xv_de_piracicaba", name: "XV de Piracicaba", logoPath: "/escudos_2025/xv_de_piracicaba.svg" },
  { id: "zumbi", name: "Zumbi", logoPath: "/escudos_2025/zumbi.svg" },
]

// Lista filtrada apenas com times que têm logos em PNG
export const TEAMS: Team[] = ALL_TEAMS.filter(team => team.logoPath.endsWith('.png'))

// Helper function to get team name by ID for API calls
export const getTeamNameById = (teamId: string): string => {
  const team = ALL_TEAMS.find(t => t.id === teamId)
  return team?.name?.toLowerCase().replace(/\s+/g, '-').replace(/[áàâã]/g, 'a').replace(/[éê]/g, 'e').replace(/[íî]/g, 'i').replace(/[óôõ]/g, 'o').replace(/[úû]/g, 'u').replace(/ç/g, 'c') || teamId
}