[build]
  command = "pnpm run build"
  publish = ".next"
  functions = "netlify/functions"

# Incluir assets públicos nas funções
[functions]
  included_files = ["public/**/*"]

[[plugins]]
  package = "@netlify/plugin-nextjs"